fix!: updated postgresql and removed manual secret copying
defenseunicorns/uds-package-confluence pull request #29
Opened 2024-08-01 15:54 UTC by JoeHCQ1

Closes #28

2024-08-01 21:37 UTC, JoeHCQ1 commented
Reviewers, the upgrade step fails on bafd88c4e1f6baf6931d8c9ceb46d42a7f1fbe1d. I do not believe this should prevent merging because:

1. We have no (known) users of this package.
2. The error would be fairly easy to solve if necessary, the old version of this package put the secret in one-place, and when upgrading, it'd appear the operator does not generate a new secret, therefore, confluence never comes up and is stuck with a config error.

LTMK if this needs to be fixed. I think the simplest approach would be to leave the manual secret copy in, only modify it to copy from the old secret if needed, and then back that out in a subsequent PR.

2024-08-02 17:36 UTC, corang requested changes
I'm pretty sure all of this will be superseded by https://github.com/defenseunicorns/uds-package-confluence/pull/34 since it's such a large change to move to the upstream chart. Unless I missed something this can most likely be closed

2024-08-02 17:36 UTC, corang commented on .github/workflows/test.yaml
> +      - name: Debug Cluster
should be removed before merge to main

2024-08-02 17:36 UTC, corang commented on .gitignore
> +confluence_license.txt
What's this for?

2024-08-02 17:36 UTC, corang commented on bundle/uds-bundle.yaml
> -    ref: 1.10.1-uds.4-upstream
We usually let renovate do this, if it's not picking it up we need to check our renovate config

2024-08-02 17:36 UTC, corang commented on common/zarf.yaml
> +    actions:
This only works when we're using the postgres operator package from uds, there are a bunch of other possible deployments of this, e.g. using RDS

2024-08-02 17:48 UTC, JoeHCQ1 commented
OBE

2024-08-02 17:48 UTC, closed without merging