draft: Feat enable confluence clustering by default
defenseunicorns/uds-package-confluence pull request #46
Opened 2024-08-07 21:04 UTC by JoeHCQ1

2024-08-20 21:07 UTC, corang requested changes
So my understanding of the status of this is that we can't get clustering to work while the pods have istio sidecars even with messing with mtls and destinationrules?

2024-08-20 21:07 UTC, corang commented on docs/clustering.md
> +### Clustering w/o Istio
I'm not sure this is something we should support / document at all to be honest

2024-08-20 21:07 UTC, corang commented on src/namespace/confluence-ns.yaml
> +---
Why add these a bunch of places?

2024-08-20 21:32 UTC, JoeHCQ1 commented on chart/Chart.yaml
> -version: 0.1.0
OK

2024-08-20 21:34 UTC, JoeHCQ1 commented on src/namespace/confluence-ns.yaml
> +---
I still tend to add those so if ever concatenated the yaml files remain valid. I think these in particular may have come up when I ran yamllint locally.

2024-08-20 21:37 UTC, JoeHCQ1 commented on docs/clustering.md
> +### Clustering w/o Istio
Is the comment on line 41 or line 39?

Re Line 39:  it'd mostly just be useful to future me or you whenever we're asked to make it work with Istio.

Re Line 41:  as my client wants confluence and will be serving a very large user load, we'll have to be ready to provide a clustered Confluence installation of some sort. Unless we tell them to put it totally off-cluster, as things stand we will be providing them Confluence clustered without Istio, and so without encryption in transit.

2024-08-20 21:37 UTC, JoeHCQ1 commented on common/zarf.yaml
> -        version: 0.1.0
OK - boring ;)

2024-09-09 15:14 UTC, JoeHCQ1 commented
To throw an update in here: we have evidence the clustering can work, and some pointers on how to get it to work. I don't know if we want to chance the consequences of long-lived branches though by not merging this work in even with clustering in a still broken state.

2024-10-17 02:38 UTC, andrewg-xyz approved these changes
Maybe add a test for clustering?

2024-10-18 19:19 UTC, Michael-Kruggel commented
Replying for posterity, testing for clustering would require some level of click-ops

2024-10-18 19:19 UTC, merged